# Generated by Django 3.2.14 on 2022-11-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantem',
            options={'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.CreateModel(
            name='CursoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(default=None, null=True, verbose_name='Fecha de inicio')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.categoria')),
                ('estudiantes', models.ManyToManyField(to='cac.EstudianteM')),
            ],
        ),
    ]
