# Generated by Django 3.2.14 on 2022-11-16 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Comsion:')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='comision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cac.comision'),
        ),
    ]
