# Generated by Django 3.2.14 on 2022-11-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0002_auto_20221116_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='comision',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Imagen:'),
        ),
    ]
